server:
  port: 8081
spring:
  application:
    name: UserService
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: configserver:http://localhost:8085

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instance:
      RatingHotelCircuitBreaker:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        eventConsumerBufferSize: 10
        automaticTransactionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      RatingHotelCircuitRetry:
        max-attempt: 3
        wait-duration: 5s
  ratelimiter:
    instances:
      RatingHotelCircuitRateLimiter:
        limit-refresh-period: 4s
        limit-of-period: 2
        timeout-duration: 0s


